spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mapmory
    username: mapmory
    password: qwe123
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
